services:
  app:
    build:
      context: /home/mateusz/Repositories/ItemSwapBackend/src/main/java/pl/mateusz/swap_items_backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /home/mateusz/Files:/home/mateusz/Files
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ItemSwapApp
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_STORAGE_PATH: /home/mateusz/Files

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ItemSwapApp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata:
